import { ServiceAreaZone } from "../generated/prisma/enums";

/** Legacy catch-all; keep for old `Lead.areaId` rows — never shown on public pickers. */
export const LEGACY_AREA_SLUGS_EXCLUDED_FROM_PUBLIC = ["onnanno"] as const;

export type AreaSeedRow = {
  slug: string;
  /** Romanized / short English label (search + exports). */
  name: string;
  nameBn: string;
  nameEn?: string | null;
  zone: ServiceAreaZone;
  isPopular: boolean;
  sortOrder: number;
  /** When false, row stays in DB for FK history only. */
  isActive?: boolean;
};

/**
 * Initial Dhaka / peri-urban coverage — upserted by `prisma/seed.ts`.
 * Order follows product list; `sortOrder` is stable for admin tuning.
 */
export const AREA_SEED_ROWS: readonly AreaSeedRow[] = [
  // ——— NORTH_DHAKA ———
  {
    slug: "gabtoli",
    name: "Gabtoli",
    nameBn: "গাবতলী",
    zone: ServiceAreaZone.NORTH_DHAKA,
    isPopular: true,
    sortOrder: 10,
  },
  {
    slug: "mirpur",
    name: "Mirpur",
    nameBn: "মিরপুর",
    zone: ServiceAreaZone.NORTH_DHAKA,
    isPopular: true,
    sortOrder: 20,
  },
  {
    slug: "mirpur-6",
    name: "Mirpur 6",
    nameBn: "মিরপুর-৬",
    zone: ServiceAreaZone.NORTH_DHAKA,
    isPopular: false,
    sortOrder: 30,
  },
  {
    slug: "mirpur-11-pallabi",
    name: "Mirpur 11 / Pallabi",
    nameBn: "মিরপুর-১১ / পল্লবী",
    zone: ServiceAreaZone.NORTH_DHAKA,
    isPopular: false,
    sortOrder: 40,
  },
  {
    slug: "kalshi",
    name: "Kalshi",
    nameBn: "কালশী",
    zone: ServiceAreaZone.NORTH_DHAKA,
    isPopular: true,
    sortOrder: 50,
  },
  {
    slug: "rupnagar",
    name: "Rupnagar",
    nameBn: "রূপনগর",
    zone: ServiceAreaZone.NORTH_DHAKA,
    isPopular: false,
    sortOrder: 60,
  },
  {
    slug: "shyamoli",
    name: "Shyamoli",
    nameBn: "শ্যামলী",
    zone: ServiceAreaZone.NORTH_DHAKA,
    isPopular: false,
    sortOrder: 70,
  },
  {
    slug: "agargaon",
    name: "Agargaon",
    nameBn: "আগারগাঁও",
    zone: ServiceAreaZone.NORTH_DHAKA,
    isPopular: false,
    sortOrder: 80,
  },
  {
    slug: "kachukhet",
    name: "Kachukhet",
    nameBn: "কচুক্ষেত",
    zone: ServiceAreaZone.NORTH_DHAKA,
    isPopular: false,
    sortOrder: 90,
  },
  {
    slug: "cantonment",
    name: "Cantonment",
    nameBn: "ক্যান্টনমেন্ট",
    zone: ServiceAreaZone.NORTH_DHAKA,
    isPopular: false,
    sortOrder: 100,
  },
  {
    slug: "banani",
    name: "Banani",
    nameBn: "বনানী",
    zone: ServiceAreaZone.NORTH_DHAKA,
    isPopular: false,
    sortOrder: 110,
  },
  {
    slug: "gulshan",
    name: "Gulshan",
    nameBn: "গুলশান",
    zone: ServiceAreaZone.NORTH_DHAKA,
    isPopular: false,
    sortOrder: 120,
  },
  {
    slug: "badda",
    name: "Badda",
    nameBn: "বাড্ডা",
    zone: ServiceAreaZone.NORTH_DHAKA,
    isPopular: true,
    sortOrder: 130,
  },
  {
    slug: "merul-badda",
    name: "Merul Badda",
    nameBn: "মেরুল বাড্ডা",
    zone: ServiceAreaZone.NORTH_DHAKA,
    isPopular: false,
    sortOrder: 140,
  },
  {
    slug: "aftab-nagar",
    name: "Aftab Nagar",
    nameBn: "আফতাবনগর",
    zone: ServiceAreaZone.NORTH_DHAKA,
    isPopular: true,
    sortOrder: 150,
  },
  {
    slug: "rampura",
    name: "Rampura",
    nameBn: "রামপুরা",
    zone: ServiceAreaZone.NORTH_DHAKA,
    isPopular: true,
    sortOrder: 160,
  },
  {
    slug: "bonshri",
    name: "Bonshri",
    nameBn: "বনশ্রী",
    zone: ServiceAreaZone.NORTH_DHAKA,
    isPopular: false,
    sortOrder: 170,
  },
  {
    slug: "khilkhet",
    name: "Khilkhet",
    nameBn: "খিলক্ষেত",
    zone: ServiceAreaZone.NORTH_DHAKA,
    isPopular: true,
    sortOrder: 180,
  },
  {
    slug: "nikunjo",
    name: "Nikunjo",
    nameBn: "নিকুঞ্জ",
    zone: ServiceAreaZone.NORTH_DHAKA,
    isPopular: false,
    sortOrder: 190,
  },
  {
    slug: "airport-area",
    name: "Airport area",
    nameBn: "বিমানবন্দর",
    zone: ServiceAreaZone.NORTH_DHAKA,
    isPopular: false,
    sortOrder: 200,
  },
  {
    slug: "uttara",
    name: "Uttara",
    nameBn: "উত্তরা",
    zone: ServiceAreaZone.NORTH_DHAKA,
    isPopular: true,
    sortOrder: 210,
  },
  {
    slug: "diyabari",
    name: "Diyabari",
    nameBn: "দিয়াবাড়ি",
    zone: ServiceAreaZone.NORTH_DHAKA,
    isPopular: false,
    sortOrder: 220,
  },
  {
    slug: "tongi-adjacent-dhaka",
    name: "Tongi adjacent",
    nameBn: "টঙ্গী সংলগ্ন",
    zone: ServiceAreaZone.NORTH_DHAKA,
    isPopular: false,
    sortOrder: 230,
  },

  // ——— CENTRAL_DHAKA ———
  {
    slug: "farmgate",
    name: "Farmgate",
    nameBn: "ফার্মগেট",
    zone: ServiceAreaZone.CENTRAL_DHAKA,
    isPopular: false,
    sortOrder: 300,
  },
  {
    slug: "karwan-bazar",
    name: "Karwan Bazar",
    nameBn: "কারওয়ান বাজার",
    zone: ServiceAreaZone.CENTRAL_DHAKA,
    isPopular: false,
    sortOrder: 310,
  },
  {
    slug: "tejgaon",
    name: "Tejgaon",
    nameBn: "তেজগাঁও",
    zone: ServiceAreaZone.CENTRAL_DHAKA,
    isPopular: false,
    sortOrder: 320,
  },
  {
    slug: "mohakhali",
    name: "Mohakhali",
    nameBn: "মহাখালী",
    zone: ServiceAreaZone.CENTRAL_DHAKA,
    isPopular: false,
    sortOrder: 330,
  },
  {
    slug: "moghbazar",
    name: "Moghbazar",
    nameBn: "মগবাজার",
    zone: ServiceAreaZone.CENTRAL_DHAKA,
    isPopular: false,
    sortOrder: 340,
  },
  {
    slug: "malibagh",
    name: "Malibagh",
    nameBn: "মালিবাগ",
    zone: ServiceAreaZone.CENTRAL_DHAKA,
    isPopular: false,
    sortOrder: 350,
  },
  {
    slug: "shantinagar",
    name: "Shantinagar",
    nameBn: "শান্তিনগর",
    zone: ServiceAreaZone.CENTRAL_DHAKA,
    isPopular: false,
    sortOrder: 360,
  },
  {
    slug: "ramna",
    name: "Ramna",
    nameBn: "রমনা",
    zone: ServiceAreaZone.CENTRAL_DHAKA,
    isPopular: false,
    sortOrder: 370,
  },
  {
    slug: "shahbag",
    name: "Shahbag",
    nameBn: "শাহবাগ",
    zone: ServiceAreaZone.CENTRAL_DHAKA,
    isPopular: false,
    sortOrder: 380,
  },
  {
    slug: "paltan",
    name: "Paltan",
    nameBn: "পল্টন",
    zone: ServiceAreaZone.CENTRAL_DHAKA,
    isPopular: false,
    sortOrder: 390,
  },
  {
    slug: "motijheel",
    name: "Motijheel",
    nameBn: "মতিঝিল",
    zone: ServiceAreaZone.CENTRAL_DHAKA,
    isPopular: false,
    sortOrder: 400,
  },
  {
    slug: "komlapur",
    name: "Komlapur",
    nameBn: "কমলাপুর",
    zone: ServiceAreaZone.CENTRAL_DHAKA,
    isPopular: false,
    sortOrder: 410,
  },
  {
    slug: "khilgaon",
    name: "Khilgaon",
    nameBn: "খিলগাঁও",
    zone: ServiceAreaZone.CENTRAL_DHAKA,
    isPopular: false,
    sortOrder: 420,
  },

  // ——— OLD_DHAKA ———
  {
    slug: "islampur",
    name: "Islampur",
    nameBn: "ইসলামপুর",
    zone: ServiceAreaZone.OLD_DHAKA,
    isPopular: false,
    sortOrder: 500,
  },
  {
    slug: "chawk-bazar",
    name: "Chawk Bazar",
    nameBn: "চকবাজার",
    zone: ServiceAreaZone.OLD_DHAKA,
    isPopular: false,
    sortOrder: 510,
  },
  {
    slug: "lalbag",
    name: "Lalbag",
    nameBn: "লালবাগ",
    zone: ServiceAreaZone.OLD_DHAKA,
    isPopular: false,
    sortOrder: 520,
  },
  {
    slug: "bangshal",
    name: "Bangshal",
    nameBn: "বংশাল",
    zone: ServiceAreaZone.OLD_DHAKA,
    isPopular: false,
    sortOrder: 530,
  },
  {
    slug: "sutrapur",
    name: "Sutrapur",
    nameBn: "সূত্রাপুর",
    zone: ServiceAreaZone.OLD_DHAKA,
    isPopular: false,
    sortOrder: 540,
  },
  {
    slug: "sadarghat",
    name: "Sadarghat",
    nameBn: "সদরঘাট",
    zone: ServiceAreaZone.OLD_DHAKA,
    isPopular: false,
    sortOrder: 550,
  },
  {
    slug: "wari",
    name: "Wari",
    nameBn: "ওয়ারী",
    zone: ServiceAreaZone.OLD_DHAKA,
    isPopular: false,
    sortOrder: 560,
  },
  {
    slug: "gendaria",
    name: "Gendaria",
    nameBn: "গেন্ডারিয়া",
    zone: ServiceAreaZone.OLD_DHAKA,
    isPopular: false,
    sortOrder: 570,
  },
  {
    slug: "narinda",
    name: "Narinda",
    nameBn: "নারিন্দা",
    zone: ServiceAreaZone.OLD_DHAKA,
    isPopular: false,
    sortOrder: 580,
  },

  // ——— SOUTH_DHAKA ———
  {
    slug: "jatrabari",
    name: "Jatrabari",
    nameBn: "যাত্রাবাড়ী",
    zone: ServiceAreaZone.SOUTH_DHAKA,
    isPopular: true,
    sortOrder: 600,
  },
  {
    slug: "sayedabad",
    name: "Sayedabad",
    nameBn: "সায়েদাবাদ",
    zone: ServiceAreaZone.SOUTH_DHAKA,
    isPopular: false,
    sortOrder: 610,
  },
  {
    slug: "shonir-akhra",
    name: "Shonir Akhra",
    nameBn: "শনির আখড়া",
    zone: ServiceAreaZone.SOUTH_DHAKA,
    isPopular: false,
    sortOrder: 620,
  },
  {
    slug: "dholaipar",
    name: "Dholaipar",
    nameBn: "ধোলাইপাড়",
    zone: ServiceAreaZone.SOUTH_DHAKA,
    isPopular: false,
    sortOrder: 630,
  },
  {
    slug: "postagola",
    name: "Postagola",
    nameBn: "পোস্তগোলা",
    zone: ServiceAreaZone.SOUTH_DHAKA,
    isPopular: false,
    sortOrder: 640,
  },
  {
    slug: "demra",
    name: "Demra",
    nameBn: "ডেমরা",
    zone: ServiceAreaZone.SOUTH_DHAKA,
    isPopular: true,
    sortOrder: 650,
  },
  {
    slug: "sarulia",
    name: "Sarulia",
    nameBn: "সারুলিয়া",
    zone: ServiceAreaZone.SOUTH_DHAKA,
    isPopular: true,
    sortOrder: 660,
  },
  {
    slug: "matuail",
    name: "Matuail",
    nameBn: "মাতুয়াইল",
    zone: ServiceAreaZone.SOUTH_DHAKA,
    isPopular: false,
    sortOrder: 670,
  },
  {
    slug: "dania",
    name: "Dania",
    nameBn: "ধনিয়া",
    zone: ServiceAreaZone.SOUTH_DHAKA,
    isPopular: false,
    sortOrder: 680,
  },

  // ——— WEST_DHAKA ———
  {
    slug: "mohammadpur",
    name: "Mohammadpur",
    nameBn: "মোহাম্মদপুর",
    zone: ServiceAreaZone.WEST_DHAKA,
    isPopular: true,
    sortOrder: 700,
  },
  {
    slug: "boshila",
    name: "Boshila",
    nameBn: "বছিলা",
    zone: ServiceAreaZone.WEST_DHAKA,
    isPopular: true,
    sortOrder: 710,
  },
  {
    slug: "adabor",
    name: "Adabor",
    nameBn: "আদাবর",
    zone: ServiceAreaZone.WEST_DHAKA,
    isPopular: false,
    sortOrder: 720,
  },
  {
    slug: "dhanmondi",
    name: "Dhanmondi",
    nameBn: "ধানমন্ডি",
    zone: ServiceAreaZone.WEST_DHAKA,
    isPopular: false,
    sortOrder: 730,
  },
  {
    slug: "jigatala",
    name: "Jigatala",
    nameBn: "জিগাতলা",
    zone: ServiceAreaZone.WEST_DHAKA,
    isPopular: false,
    sortOrder: 740,
  },
  {
    slug: "hazaribagh",
    name: "Hazaribagh",
    nameBn: "হাজারীবাগ",
    zone: ServiceAreaZone.WEST_DHAKA,
    isPopular: false,
    sortOrder: 750,
  },
  {
    slug: "kamrangir-char",
    name: "Kamrangir Char",
    nameBn: "কামরাঙ্গীরচর",
    zone: ServiceAreaZone.WEST_DHAKA,
    isPopular: false,
    sortOrder: 760,
  },
  {
    slug: "keraniganj",
    name: "Keraniganj",
    nameBn: "কেরানীগঞ্জ",
    zone: ServiceAreaZone.WEST_DHAKA,
    isPopular: true,
    sortOrder: 770,
  },

  // ——— OUTSIDE_DHAKA ———
  {
    slug: "savar",
    name: "Savar",
    nameBn: "সাভার",
    zone: ServiceAreaZone.OUTSIDE_DHAKA,
    isPopular: true,
    sortOrder: 800,
  },
  {
    slug: "ashulia",
    name: "Ashulia",
    nameBn: "আশুলিয়া",
    zone: ServiceAreaZone.OUTSIDE_DHAKA,
    isPopular: false,
    sortOrder: 810,
  },
  {
    slug: "hemayetpur",
    name: "Hemayetpur",
    nameBn: "হেমায়েতপুর",
    zone: ServiceAreaZone.OUTSIDE_DHAKA,
    isPopular: false,
    sortOrder: 820,
  },
  {
    slug: "amin-bazar",
    name: "Amin Bazar",
    nameBn: "আমিনবাজার",
    zone: ServiceAreaZone.OUTSIDE_DHAKA,
    isPopular: false,
    sortOrder: 830,
  },
  {
    slug: "dhamrai",
    name: "Dhamrai",
    nameBn: "ধামরাই",
    zone: ServiceAreaZone.OUTSIDE_DHAKA,
    isPopular: false,
    sortOrder: 840,
  },
  {
    slug: "narayanganj-adjacent",
    name: "Narayanganj adjacent",
    nameBn: "নারায়ণগঞ্জ সংলগ্ন",
    zone: ServiceAreaZone.OUTSIDE_DHAKA,
    isPopular: false,
    sortOrder: 850,
  },
  {
    slug: "tongi-gazipur-adjacent",
    name: "Tongi / Gazipur adjacent",
    nameBn: "টঙ্গী / গাজীপুর সংলগ্ন",
    zone: ServiceAreaZone.OUTSIDE_DHAKA,
    isPopular: false,
    sortOrder: 860,
  },
];
